name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      
      
      # Build using BuildHeadless
    - name: Setup Env
      run: |
        # make file runnable, might not be necessary
        mkdir build && cd build
        cmake -GNinja ..
    - name: Build
      run: |
        cd build
        ninja
