name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      # Install needed packages
    - name: Install g++ / gcc
      run: sudo apt-get install g++ gcc             -y
    - name: Install gcc-multilib
      run: sudo apt-get install gcc-multilib        -y
    - name: Install g++-multilib
      run: sudo apt-get install g++-multilib        -y
    - name: Install xorriso
      run: sudo apt-get install xorriso             -y
    - name: Install nasm
      run: sudo apt-get install nasm                -y
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install build-essential
      run: sudo apt-get install build-essential
    - name: Install bison
      run: sudo apt-get install bison
    - name: Install flex
      run: sudo apt-get install flex
    - name: Install libgmp3-dev
      run: sudo apt-get install libgmp3-dev
    - name: Install libmpc-dev
      run: sudo apt-get install libmpc-dev
    - name: Install libmpfr-dev
      run: sudo apt-get install libmpfr-dev
    - name: Install texinfo
      run: sudo apt-get install texinfo
    - name: Install libcloog-isl-dev	
      run: sudo apt-get install libcloog-isl-dev	
    - name: Install libisl-dev	
      run: sudo apt-get install libisl-dev	
      
      
      # Build using BuildHeadless
    - name: Setup Env
      run: |
        # make file runnable, might not be necessary
        mkdir build && cd build
        cmake -GNinja ..
    - name: Build Tools
      run: |
        ninja build_tools
    - name: Build
      run: |
        ninja
