name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'We have detected this is a Stale issue, and will be deleted soon! If you still need to get this issue fixed, try reporting again!'
        stale-pr-message: 'We have detected this is a Stale pull request, since Stale pull requests can have major merge issues we can no longer merge. Try pulling again!'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
